### ISSUE TITLE
Using volo to create a template does not get the HEAD revision

### ISSUE THREAD

**Issue by bemjb** [mozilla/mortar-list-detail#3]
I used volo to create the template, and as surprised that it has a different version of mortar-list-detail than is on github. It looks like it's a little bit behind the version on github. Perhaps it should be mentioned that the volo version is sometimes not in sync with the latest you would get with a git clone?

Thanks.

**Comment by brianpeiris** [comment]
Looks like volo uses the latest "release" version. Please make a new release.
