### ISSUE TITLE
ghdeploy not working on FirefoxOS Simulator

### ISSUE THREAD

**Issue by fczuardi** [mozilla/mortar-list-detail#5]
Steps to reproduce:

volo create myapp mozilla/mortar-list-detail
cd myapp
volo build
volo ghdeploy

Then I wait and open my FirefosOS Simulator on my Firefox nightly by adding this url on the Simulator dashboard:

http://fczuardi.github.com/myapp/manifest.webapp

FirefoxOS Simulator then opens and displays a github 404 page error:

“There isnt a Github Page Here”

I've tried to edit the manifest and replace the launch_path to /index.html and it works when I use the "Add Directory" of the simulator instead of "Add URL".

The github hosted urls seems to work, I can access the icons and the app urls for instance in the browser.

**Comment by jlongster** [comment]
Try changing the "launch_path" to "/myapp/". You are right that it needs to be changed, but it's the complete path from the domain. Sorry about that, we need to make a better note about it.
