### ISSUE TITLE
button [+] doesn't work

### ISSUE THREAD

**Issue by marti1125** [mozilla/mortar-list-detail#6]
![a](https://f.cloud.github.com/assets/223240/93421/a0920be6-6622-11e2-9cd6-791edb0bd7c3.png)

**Comment by jlongster** [comment]
Unfortunately this is a bug in the Firefox Simulator where it says it supports touch events but it never fires them. We are working on fixing that asap.

**Comment by wfwalker** [comment]
James, we are also working to do better touch event support in the Simulator, let's coordinate efforts
