### ISSUE TITLE
Mortar not working in Simulator

### ISSUE THREAD

**Issue by jrburke** [mozilla/mortar-list-detail#8]
A place to discuss an issue that came up in this b2g thread:

http://groups.google.com/group/mozilla.dev.b2g/browse_thread/thread/970ef5c83a86e5b2#

There were some people that had trouble getting mortar/requirejs-based projects working in the simulator, but worked outside of it. I tried to reproduce by doing the following:

On command line I entered this command, using volo 0.2.7 on OS X 10.8.2:

```
volo create myapp mozilla/mortar-list-detail
```

Then, I launched Aurora, and made sure it was up to date. I then launched the Simulator. I am using verion 2.0pre5 of the Simulator. I opened Tools, Web Developer, Firefox OS Simulator. In the simulator:
- Clicked Add directory
- Chose the myapp/www/manifest.webapp file
- The simulator launched, and I clicked on the "My App" icon.
- It just showed a directory listing for some reason. I believe this is a Simulator bug. I clicked on the "index.html" file in that directory listing.
- The app loaded and worked as expected.

If you have trouble with this sequence or can provide a different sequence of events, or you just need help going through some of the steps, leave a comment below.

**Comment by jrburke** [comment]
Closing this, as it works for me, but we can reopen if further discussion identifies a bug.

**Comment by jlongster** [comment]
Hm, that was a bug in the "launch_path" entry in the manifest file, but I fixed it to be "/index.html" over a week ago. Are you saying that you can reproduce it anymore or that you think the bug is elsewhere? If you're still seeing a directory listing I think we need to look into it.

**Comment by jrburke** [comment]
Ah, yes, looks like the repo just needs a new version tag applied to it:

https://github.com/mozilla/mortar-list-detail/compare/v0.1.3...master

when doing `volo create myapp mozilla/mortar-list-detail` since there is no specific branch name mentioned and the repo has at least one version tag, it grabs the most recent version tag, which is v0.1.3 at the moment.

**Comment by jlongster** [comment]
Oh I didn't realize that! No wonder people were still experiencing this problem sometimes. Thanks!

**Comment by jrburke** [comment]
The other option is to just remove the version tags, so that master is always fetched. Depends on how you want to develop the app, "always up to date" (no version tags) or "checkpoint, new, possibly unstable dev, checkpoint".

**Comment by tofumatt** [comment]
master should never be broken, but especially not on a repo developers directly check out and use.
- tofumatt | http://tofumatt.com

**Comment by jlongster** [comment]
We develop the mortar templates so that master shouldn't ever be broken, so we could do without tags. I remember at one point wenzel wanted tags so that the devhub could link to specific tags. We should probably just remove them.

**Comment by tofumatt** [comment]
Yeah, we should always just link to the current version (master), so devs get the best we have to offer.
- tofumatt | http://tofumatt.com

**Comment by fwenzel** [comment]
The only problem with not tagging is, when people download a version with a bug, they won't know that "this is version 1.3, and 1.4 fixed this bug". But yeah I see the reasoning for pointing to a stable master.

When you remove the tags, make sure the links on the devhub are fixed first.

**Comment by jlongster** [comment]
True, but it's arguably pretty easy to get the commit number as well. Also, `volo create` doesn't copy any of the git stuff so they really don't even know what version they are on.

I won't take them out right now, but maybe soon!

**Comment by marcbaechinger** [comment]
Thanks to all. Unfortunatly it's not working for me.

It fails with saying "My App is having problems" "My App is not loading properly"
In the error console it says NO SETTINGS PERMISSION FOR app://system.gaiamobile.org

It's ok for now. So I'm not going to demo app templates in the simulator but in Firefox with responsive view only att the app day.
Thanks for trying to help. I'll be back to this when I was able to run it. I will report what went wrong.

**Comment by marcbaechinger** [comment]
It works with the most recent version like jrburke told me. Thank you very much.
